### ISSUE TITLE
Write initial version of ocdsdata library

### ISSUE THREAD

**Issue by robredpath** [open-contracting/ocdsdata#1]
The ocdsdata library will be a Python library to obtain OCDS data from one or more publishers' APIs and provide methods to store that data in an intermediate form for further processing. 

In its initial form, it should:
- have a class per publisher, for a handful of publishers, drawing on existing fetch scripts from sample-data where appropriate
- have an abstract class as a parent for each per-publisher class
- have sufficient functionality to provide representative data for the rest of the process

In its initial form, it's ok for it to not have pagination/resume functionality, random selection or arbitrary params. However, we shouldn't do anything that precludes adding these, and if it's easy to add them at the same time, it's ok to do that. 

Internal - this is all based on:  https://docs.google.com/document/d/1Am23Fk7-0M0fusd7Lgw_V-7-O17CbZykd_XYHCjxPCY/edit#bookmark=id.dts74vmkn30g

**Comment by robredpath** [comment]
@kindly to set out the initial working practice here, @Bjwebb to review and comment as necessary

**Comment by jpmckinney** [comment]
I believe this is done.
