### ISSUE TITLE
Use case: report on how good a source is 

### ISSUE THREAD

**Issue by odscjames** [open-contracting/ocdsdata#105]
From @timgdavies  in #103 

> As an analyst reviewing a publishers data I want to be able to tell them about any issues that might make their data difficult to work with so that they can fix their data at source and future users can work with the data without encoding issues or other problems.

**Comment by jpmckinney** [comment]
My understanding of this issue is that the issues to be reported to the publisher are with respect to the quality of the API and/or bulk download, e.g. encoding issues, HTTP 500 errors, low throughput, non-functional API filters, etc. Is that correct?

**Comment by odscjames** [comment]
Yes. Specifically, any errors we manage to recover from (eg, Control codes in files that we have to remove) we still want logged somewhere so they can be reported to the publisher later.
