### ISSUE TITLE
Establish a place for people to share/store useful queries

### ISSUE THREAD

**Issue by robredpath** [open-contracting/ocdsdata#110]
I'd like to store the queries that people are starting to use in a vaguely organised way, but in a place that people can easily access and edit them - I'm thinking GH wiki, at least initially. 

Could people from ODSC and ILDA let me know perhaps 5 initial examples of answers to the question "What are you trying to do with the data?" so that we can keep some semblance of order to the wiki? 

@timgdavies @duncandewhurst @Tim0th1 @yolile @tian2992 @juanpane ^^

**Comment by jpmckinney** [comment]
Noting this script in a branch, to ensure it isn't lost: https://github.com/open-contracting/ocdsdata/compare/sql-scripts

**Comment by yolile** [comment]
I already "transformed" some of the queries used to make the structure validation report here: https://docs.google.com/document/d/1zqtBsiC5b-QSjZYwq3rCu7JYpOn5HTtiC7iekv26YaM/edit#heading=h.udasz8n181do

**Comment by duncandewhurst** [comment]
So far (in the context of working on OCDS for Infrastructure) I've been:

* Understanding which OCDS fields are in the data
* Checking how the releases and records model is used
* Searching for contracting processes related to a given project (by title, description etc.)

The doc shared by @yolile gives a good overview of the types of question we ask when reviewing data

**Comment by robredpath** [comment]
@yolile that looks perfect! 

In terms of a place to store and share queries that people will be running on the ocdsdata server, is there a need for another place (eg the GH wiki?) or will that doc suffice?

**Comment by timgdavies** [comment]
I like the idea of being able to save queries in Redash (given it has features for this). Even if they are not run from there, they can be copied out to run in other tools.

**Comment by duncandewhurst** [comment]
In lieu of Redash being installed on the server and with a view to documenting the Australia data review I'll be carrying out this week, I've been working on converting the [data structure feedback methodology](https://docs.google.com/document/d/1zqtBsiC5b-QSjZYwq3rCu7JYpOn5HTtiC7iekv26YaM/edit#) into a [colaboratory (jupyter) notebook](https://colab.research.google.com/drive/1fF_liJkuxboF2zt9z4zdEB2YahbsU0sh#scrollTo=8npu2NX9MGBn) which connects to the ocdsdata server.

I've copied across the queries that @yolile transformed for postgresql and transformed or added queries to:

* Return additional fields reported by CoVE
* Return validation errors reported by CoVE 
* Return extensions reported by CoVE
* Return extensions declared in the package metadata (for when the check stage of the data load wasn't run)
* Return a list of organizations identifier schemes used (for both OCDS 1.0 and 1.1)
* Return a list of ocids with multiple releases (to check how releases and records model is used)
* Return a list of tags and releases for ocids with multiple releases (to check how releases and records model is used) 
* Return a list of item classification schemes used 

I'll use this as the basis for the australia data review so will add more queries to it as I work on that this week (once the scraper has finished)

@robredpath I created a new key pair to use for the connection from the notebook and added the public key to the ocdsdata server

**Comment by robredpath** [comment]
I don't think there's anything else to do here right now - closing
