### ISSUE TITLE
Installation improvement: Allow setting DB_URI in a config file

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocdsdata#114]
For example, we might have a `.config/ocdsdata.conf` file that is read by Python's `ConfigParser` to retrieve the `DB_URI`. We might add a subcommand to the CLI to write/update this file.

If an environment variable is present, it should likely take precedence. The CLI subcommand that does Fetch-Gather-Load can print which DB_URI it is using, for easier troubleshooting.

**Comment by tian2992** [comment]
Currently working on it on #117

**Comment by tian2992** [comment]
Pending check on #117 to merge to force defaults set or DB_URI in order to run.
