### ISSUE TITLE
DB Config Loading can't cope with a .pgpass with no correct entry in it, or one with incorrect permissions

### ISSUE THREAD

**Issue by odscjames** [open-contracting/ocdsdata#124]
(You'll want to put "print(DB_URI)" in config.py to help see this)

Imagine a situation where the default DB connection strings are fine. Make sure there is no .pgpass file and there is no Environmental variable.  Run cli, and you should see:

>  postgresql://ocdsdata:ocdsdata@localhost/ocdsdata

All is good.

Now create a .pgpass file. Leave it empty, or put another entry in for a different database. This scenario could arise when one user account uses several different apps that connect to different Postgres DB's. Now run it, and you'll see:

> postgresql://ocdsdata:None@localhost/ocdsdata

And it will crash with 

> FATAL:  password authentication failed for user "ocdsdata"

This is because we are only checking for the FileNotFound error! If the file is found but there is no entry, it returns None for password and then our script tries to use that.

Also, change file permissions on .pgpass to 644 or something and run it again. It will crash with:

> pgpasslib.InvalidPermissions: Invalid Permissions for /home/vagrant/.pgpass: 0o644

The script should catch this error, warn the user, and then ignore the contents of the file!

(See #117 )

**Comment by tian2992** [comment]
Should be covered on 87bdc73141e58ea8040668397a410d1d52fd122b at #117
