### ISSUE TITLE
Improve usage guide

### ISSUE THREAD

**Issue by yolile** [open-contracting/ocdsdata#165]
I think that is important to hava a use guide with all the options that the tool have and how to use it. 
I just updated my project recently and with the additon of the run subcomand I had no idea how to run the scraper now. (I found the some kind of instruction on the readme: "Run ocdsdata-cli run with the argument of one of the publishers you want to fetch." but this confused me as I still need to use the --run option)

**Comment by odscjames** [comment]
@yolile Does https://ocdsdata.readthedocs.io/en/master/ now help? We can close this if so. Or feedback on what you think could be improved.

**Comment by yolile** [comment]
Looks great, James, thank you very much, yes I think that you can close the
issue :)
