### ISSUE TITLE
run command: Improve interface for selecting sources

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocdsdata#169]
Since there is now a `run` subcommand, it would make sense to remove its `--run` option, and instead accept any number of sources as positional arguments (it's odd to have a required option).

We can also rename `--runall` to `--all`.

The subcommand can error if both positional arguments and `--all` are present.

Moved from https://github.com/open-contracting/ocdsdata/issues/164#issuecomment-406647257

**Comment by tian2992** [comment]
Can you re check on #168 ?
