### ISSUE TITLE
Convert Old Fetcher:  UK Contracts Finder

### ISSUE THREAD

**Issue by odscjames** [open-contracting/ocdsdata#17]
https://github.com/open-contracting/sample-data/blob/master/real-examples/uk-contracts-finder/fetch.py

**Comment by odscjames** [comment]
Re-opening as this won't load into the DB - there is a UTF error! Needs to be fixed.

**Comment by tian2992** [comment]
stashed fixes on my repo, master branch. I will wait for fixes to test-merge.

**Comment by odscjames** [comment]
Feel free to create a new branch and put it on GitHub so work can be shared!

(Altho this work is now on hold until other work is done)

**Comment by tian2992** [comment]
yea, the changes are at https://github.com/open-contracting/ocdsdata/tree/encoding_incomplete
