### ISSUE TITLE
Agree on interchange naming scheme / format / layout between Extract and Transform stage

### ISSUE THREAD

**Issue by robredpath** [open-contracting/ocdsdata#3]
In order to make it easier to collaborate on and extend the parts of the ETL pipeline, we should agree on ways in which T+L parts take data in, and therefore how E tools should output data. It's likely that we'll want to work in files, with streams and with databases over time. Initially, we're expecting to use a database backend.

**Comment by odscjames** [comment]
This feels like general work from before that could be closed now? @robredpath

**Comment by robredpath** [comment]
Yeah, this isn't necessary any more
