### ISSUE TITLE
replace requests for util.get_url_request method

### ISSUE THREAD

**Issue by yolile** [open-contracting/ocdsdata#38]

**Comment by tian2992** [comment]
Why not requests?

**Comment by jpmckinney** [comment]
I think there's just one last instance in paraguay.py

**Comment by odscjames** [comment]
> Why not requests?

Our util function has stuff around retries which just using default requests doesn't have.

I'm happy to close this now; the only uses of requests currently in there are for special cases - a POST call to get an access token or during the gather_all_download_urls stage.
