### ISSUE TITLE
Make demonstration script load data into a database backend to hold for validation and future T and L

### ISSUE THREAD

**Issue by robredpath** [open-contracting/ocdsdata#4]

**Comment by odscjames** [comment]
This feels covered by general work and #2 - can this be closed now? @robredpath

**Comment by robredpath** [comment]
ocdsdata-cli became much more than a demo script, but it seems to work for the people who are using it. Originally we expected this to be use much more as a library (and we should make sure that we don't lose sight of that) but I think it's fine for us to close this now.
