### ISSUE TITLE
Default options to cli script - currently creates new data version

### ISSUE THREAD

**Issue by odscjames** [open-contracting/ocdsdata#49]
Should the default option be to work with the last data version already on disk?

Discuss, and maybe do.

**Comment by odscjames** [comment]
Can we leave this open until the PR is merged in? Just to make sure it doesn't get forgotten about somehow.

**Comment by jpmckinney** [comment]
It looks like #57 was merged.

**Comment by odscjames** [comment]
Your right - Sorry!
