### ISSUE TITLE
Convert Old Fetcher:  Armenia

### ISSUE THREAD

**Issue by odscjames** [open-contracting/ocdsdata#5]
https://github.com/open-contracting/sample-data/blob/master/real-examples/armenia/fetch.py

**Comment by odscjames** [comment]
According to my reading of this, the URL should be https://armeps.am/ocds/release/all ? But that returns an empty dict - might this have stopped working?

**Comment by yolile** [comment]
the that works url is https://armeps.am/ocds/release (without /all)
