### ISSUE TITLE
CLI: If you specify a data version that doesn't exist, it will try and create it and start from scratch

### ISSUE THREAD

**Issue by odscjames** [open-contracting/ocdsdata#53]
I think? 

Instead, it should error politely.

**Comment by tian2992** [comment]
Would #57 fix this (?)

**Comment by odscjames** [comment]
It sounds like it would. But let's leave this ticket open till we are sure of that.

**Comment by odscjames** [comment]
It looked like 57 didn't fix this - there will be a PR shortly.

**Comment by jpmckinney** [comment]
Is this closed by #70?
