### ISSUE TITLE
Should we refactor to subcommands?

### ISSUE THREAD

**Issue by robredpath** [open-contracting/ocdsdata#63]
@kindly talked at standup this morning about a separate tool to do the checks. 

I wonder if we should take a leaf out of git's book and have subcommands?

**Comment by jpmckinney** [comment]
Why not move ocdsdata-cli to ocdskit? ocdskit already has a simple framework for subcommands.

**Comment by robredpath** [comment]
I think that's an interesting question. I'm wary of us creating omnibus tools if the functionality of each subtool isn't particularly related, but it's difficult for users to discover tools if there are lots of them.

**Comment by jpmckinney** [comment]
My perspective is that ocdsdata is a library, which may have multiple interfaces (we can imagine a GUI if there were demand for one). ocdskit is mainly a collection of CLI commands, whose implementation is 200 lines or less. If a command's logic were to grow significantly, we'd likely move it out to its own library, to keep the CLI interface thin.

**Comment by jpmckinney** [comment]
ocdsdata has been refactored to subcommands: https://github.com/open-contracting/ocdsdata/tree/master/ocdsdata/cli/commands
