### ISSUE TITLE
Convert Old Fetcher:  Colombia

### ISSUE THREAD

**Issue by odscjames** [open-contracting/ocdsdata#7]
https://github.com/open-contracting/sample-data/blob/master/real-examples/colombia/fetch.py

**Comment by odscjames** [comment]
I started on this but moved on before I could finish testing it. This is a pretty big data source! It is in it's own branch, "colombia".

**Comment by odscjames** [comment]
Basically done and in master code.

Later pages like https://api.colombiacompra.gov.co/releases/?page=5000 seem to get a pretty consistent 500 response. Need to decide how to handle this.

**Comment by tian2992** [comment]
Think this is actually working, so what would you consider missing by now?

**Comment by odscjames** [comment]
This was unclear, sorry. I have created #58 to continue discussing the point I wanted to raise and I will close this one.
