### ISSUE TITLE
If Source can't create it's folder, it should die more completely!

### ISSUE THREAD

**Issue by odscjames** [open-contracting/ocdsdata#73]
Currently base has in __init__:

        try:
            if exists and remove_dir:
                os.rmdir(self.full_directory)
                exists = False

            if not exists:
                os.makedirs(self.full_directory)
        except OSError:
            print("Error: Write permission is needed on the directory specified (or project dir).")
            return

What this means is that if it can't write to the dir, it will print a nice message but will then try and carry on! :-)

>
> We will run: 
>  - taiwan
>
> Sample mode is off.
> Error: Write permission is needed on the directory specified (or project dir).
> Now running: taiwan (Output Dir: taiwan, Data Version: 2018-04-17-11-35-18)

In this case, the CLI should stop trying to run this!

**Comment by jpmckinney** [comment]
I assume closed by #84?
