### ISSUE TITLE
Add checks that CoVE already does to the pipeline

### ISSUE THREAD

**Issue by robredpath** [open-contracting/ocdsdata#90]
We recognise that it would be useful for the output of certain checks (such as validity against schema) to be in the database alongside the data. 

This issue is to add the checks that CoVE already does (just validation if that's all there's time for, otherwise the other checks too) to an appropriate tool for a user to run and update the contents of the database with the results.

**Comment by jpmckinney** [comment]
Will such checks be implemented as different 'transforms' or 'filters'?

e.g. we have a base `Source` class for the Extract (gather/fetch) step. Should we have a base `Transform` or `Filter` class for the Transform (normalize) step? A transform would be something that accepts input data, potentially has side-effects like storing validation results, and then stores transformed data.

To give an idea of what counts as a transform conceptually, some (eventual) transforms may be:

* validation (this transform may not change the data, but the data nonetheless passes through it, so I think conceptually it's like a transform)
* 1.0 to 1.1 upgrade
* publisher-specific corrections (e.g. encoding errors)
* pulling in additional data based on external identifiers (e.g. lookup companies on OpenCorporates)

**Comment by odscjames** [comment]
We already have basic COVE checks in, thought one the tasks I have is to tidy up how these are called and how it's integrated. Currently they just check - they don't do transforms.

**Comment by odscjames** [comment]
(Transforms sound interesting but they sound like a different issue to me.)

**Comment by odscjames** [comment]
Linking this ticket to #76
