### ISSUE TITLE
Sources have to search and replace \\u0000

### ISSUE THREAD

**Issue by odscjames** [open-contracting/ocdsdata#96]
See Ukraine and Moldova. #95

Now we have 2 sources doing this, Can we do better? Should this be in framework somehow?

**Comment by robredpath** [comment]
There's probably a link here to #103 , so if we do need to make modifications to the data, we should record what we had to do.

**Comment by odscjames** [comment]
Colombia has the same problem.

**Comment by odscjames** [comment]
So changing it in the framework would be done in the util module, save_content function:

```
        with open(filepath, 'wb') as f:
            for chunk in request.iter_content(1024 ^ 2):
                if b'\\u0000' in chunk:
                    f.write(chunk.replace(b'\\u0000', b''))
                else:
                    f.write(chunk)
        return []
```

The if statement is there because at that point it would be good to log that that file had a control code we replaced, for purposes of reporting on data quality. See #105. While this function can returns errors that not what we want in this case, as an error will stop any further processing. Maybe we want the concept of a new thing, warnings? Will think about this.

**Comment by odscjames** [comment]
Noting that to duplicate for Colombia, change the for loop in that source to

> for page in range(574, 578):

**Comment by odscjames** [comment]
This is now filtered out in the framework, with a warning attached.
